# pq-tls-reverse-proxy/docker-compose.yml
version: '3.8'

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

services:
  backend-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pqc_backend
    networks:
      - backend_net
    restart: unless-stopped

  nginx-proxy:
    build:
      context: ./nginx-pqc
      dockerfile: Dockerfile
      args:
        OPENSSL_VERSION: 3.5.0
        NGINX_VERSION: 1.28.0
    container_name: pqc_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-pqc/nginx_config/conf:/etc/nginx-pq # Nginx Hauptkonfigurationen
      - ./nginx-pqc/nginx_config/ssl:/etc/nginx-pq/ssl:ro # Zertifikate read-only mounten
      - ./nginx-pqc/logs:/var/log/nginx-pq # Optional: Logs auf Host mappen
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - backend-server
    restart: unless-stopped

  client-pqc:
    build:
      context: ./client-pqc
      dockerfile: Dockerfile
      args:
        OPENSSL_VERSION: 3.5.0
    container_name: pqc_client_pqc
    volumes: # Mounten Sie das generierte Zertifikat, damit curl es verwenden kann
      - ./nginx-pqc/nginx_config/ssl/server.crt:/etc/ssl/certs/proxy_server.crt:ro
    networks:
      - frontend_net
    depends_on:
      - nginx-proxy
    stdin_open: true # Hält den Container am Laufen (wie sleep infinity)
    tty: true        # Hält den Container am Laufen

  client-classic:
    build:
      context: ./client-classic
      dockerfile: Dockerfile
    container_name: pqc_client_classic
    volumes: # Mounten Sie das generierte Zertifikat, damit curl es verwenden kann
      - ./nginx-pqc/nginx_config/ssl/server.crt:/etc/ssl/certs/proxy_server.crt:ro
    networks:
      - frontend_net
    depends_on:
      - nginx-proxy
    stdin_open: true # Hält den Container am Laufen
    tty: true        # Hält den Container am Laufen
