# nginx-oqs/nginx_config/conf/sites-available/pqc-proxy.conf
server {
    listen 80;
    listen [::]:80;
    server_name pqc-oqs.tls.proxy;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name pqc-oqs.tls.proxy; # Muss mit dem CN im Zertifikat übereinstimmen

    # SSL Zertifikate
    ssl_certificate /etc/nginx-oqs/ssl/server.crt;
    ssl_certificate_key /etc/nginx-oqs/ssl/server.key;

    # SSL Parameter einbinden
    include snippets/ssl-params.conf;

    # Logging
    access_log /var/log/nginx-oqs/pqc-proxy.access.log main;
    error_log /var/log/nginx-oqs/pqc-proxy.error.log info; # info für mehr Details beim Testen

    location / {
        proxy_pass http://backend-server:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
